### ISSUE TITLE
no module named typing

### ISSUE THREAD

**Issue by Ruch-code** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#6]
from typing import List, Optional
ImportError: No module named typing

I'm getting this error when I'm trying to use any pip install command.
I tried using pip install typing in the terminal too but it isn't working.
Looking forward to hearing from you on this

I'm using MacBook Air apple chip

**Comment by JoeHowse** [comment]
`typing` is part of the Python standard libraries, so it seems that something is wrong with your Python installation in general.  Try reinstalling Python or using a different Python distribution.  On Mac, I recommend using Python via MacPorts or Homebrew instead of using the system's built-in Python.

As this issue is not specific to this repository, I am marking it closed.
